---
title: "SCN_fluopyram_greenhouse"
author: "Mitch Roth"
date: "12/6/2017"
output: html_document
---

```{r Import data}
master <- read.csv2("SCN_Greenhouse_Test.csv", header = TRUE, sep = ",")
colnames(master)
master$Entry.Treatment
master$Exp_rep <- as.factor(master$Exp_rep)

master.qpcr <- read.csv2("SCN_qPCR_data.csv", header = TRUE, sep = ",")
colnames(master.qpcr)
master.qpcr$Trt

master.qpcr.SDS <- read.csv2("SDS_qPCR_data.csv", header = TRUE, sep = ",")
colnames(master.qpcr.SDS)
```

```{r stats}
SCN.df <- master
for(i in seq_along(SCN.df$SCN.Females)){
  SCN.df$SCN.F.Cyst[i] <- sum(SCN.df$SCN.Females[i], 
                              SCN.df$SCN.Cysts[i])
  print(SCN.df$SCN.F.Cyst[i])
}
SCN.df$SCN.F.Cyst

#determine if experimental rep had an effect on variables of interest
colnames(SCN.df)
exp.SCN.c <- t.test(SCN.Cysts ~ Exp_rep, data = SCN.df)
exp.SCN.f <- t.test(SCN.Females ~ Exp_rep, data = SCN.df)
exp.SCN.cf <- t.test(SCN.F.Cyst ~ Exp_rep, data = SCN.df)
exp.SCN.c  
exp.SCN.f
exp.SCN.cf
#Yes, experiment had an effect on these variables

#Break out data by exp_rep
exp1.df <- SCN.df[SCN.df$Exp_rep=="1",]
exp2.df <- SCN.df[SCN.df$Exp_rep=="2",]

#Determine if treatment had an overall effect on SCN cysts
SCN.c.t1 <- t.test(SCN.Cysts ~ Entry.Treatment, data = exp1.df)
SCN.c.t2 <- t.test(SCN.Cysts ~ Entry.Treatment, data = exp2.df)
SCN.c.t1
SCN.c.t2
#No effect of fluopyram on cysts in either experiment

#Determine if treatment had an overall effect on SCN females
SCN.f.t1 <- t.test(SCN.Females ~ Entry.Treatment, data = exp1.df)
SCN.f.t2 <- t.test(SCN.Females ~ Entry.Treatment, data = exp2.df)
SCN.f.t1
SCN.f.t2
#In both experiments fluopyram had significant reduction in SCN females
# exp1 P = 1.439e-07
# exp1 P = 2.969e-05

#Determine if treatment had an overall effect on SCN cysts + females
SCN.cf.t1 <- t.test(SCN.F.Cyst ~ Entry.Treatment, data = exp1.df)
SCN.cf.t2 <- t.test(SCN.F.Cyst ~ Entry.Treatment, data = exp2.df)
SCN.cf.t1
SCN.cf.t2
#In both experiments fluopyram had significant reduction in SCN cysts + females

#Determine if variety had an effect on SCN cysts
var.c.t1 <- t.test(SCN.Cysts ~ Soybean.Variety, data = exp1.df)
var.c.t2 <- t.test(SCN.Cysts ~ Soybean.Variety, data = exp2.df)
var.c.t1
var.c.t2
#No effect of variety on cysts in either experiment

#Determine if variety had an effect on SCN females
var.f.t1 <- t.test(SCN.Females ~ Soybean.Variety, data = exp1.df)
var.f.t2 <- t.test(SCN.Females ~ Soybean.Variety, data = exp2.df)
var.f.t1
var.f.t2
# In exp1, no effect of variety on females
# In exp2, variety A had signifcantly more SCN females (P = 0.01765)

var.cf.t1 <- t.test(SCN.F.Cyst ~ Soybean.Variety, data = exp1.df)
var.cf.t2 <- t.test(SCN.F.Cyst ~ Soybean.Variety, data = exp2.df)
var.cf.t1
var.cf.t2
# In exp1, no effect of variety on cysts + females
# In exp2, variety A had signifcantly more cysts + females (P = 0.02134)


#Repeat stats with qPCR data
qPCR.SCN.df <- master.qpcr
qPCR.SDS.df <- master.qpcr.SDS

#determine if experimental rep had an effect on variables of interest
qPCR.SCN.df$Experiment <- as.factor(qPCR.SCN.df$Experiment)
qPCR.SDS.df$Experiment <- as.factor(qPCR.SDS.df$Experiment)
qPCR.SCN.df$Quantity.Mean <- as.numeric(as.character(qPCR.SCN.df$Quantity.Mean))
qPCR.SDS.df$Quantity.Mean <- as.numeric(as.character(qPCR.SDS.df$Quantity.Mean))
exp.SCN.qpcr <- t.test(Quantity.Mean ~ Experiment, data = qPCR.SCN.df)
exp.SDS.qpcr <- t.test(Quantity.Mean ~ Experiment, data = qPCR.SDS.df)
exp.SCN.qpcr
exp.SDS.qpcr
#Yes, experiment had an effect on these variables

#Break out data by exp_rep
exp1.SCN.qpcr.df <- qPCR.SCN.df[qPCR.SCN.df$Experiment=="1",]
exp2.SCN.qpcr.df <- qPCR.SCN.df[qPCR.SCN.df$Experiment=="2",]
exp1.SDS.qpcr.df <- qPCR.SDS.df[qPCR.SDS.df$Experiment=="1",]
exp2.SDS.qpcr.df <- qPCR.SDS.df[qPCR.SDS.df$Experiment=="2",]

#t-tests for SCN DNA quantities in roots
SCN.qPCR.t1 <- t.test(Quantity.Mean ~ Trt, data = exp1.SCN.qpcr.df)
SCN.qPCR.t2 <- t.test(Quantity.Mean ~ Trt, data = exp2.SCN.qpcr.df)
SCN.qPCR.t1 #For exp1, fluopyram reduced SCN DNA (P = 0.0007)
SCN.qPCR.t2 #For exp2, fluopyram DIDN'T reduce SCN DNA (P = 0.07184)

#t-tests for SDS DNA quantities in roots
SDS.qPCR.t1 <- t.test(Quantity.Mean ~ Trt, data = exp1.SDS.qpcr.df)
SDS.qPCR.t2 <- t.test(Quantity.Mean ~ Trt, data = exp2.SDS.qpcr.df)
SDS.qPCR.t1 #For exp1, fluopyram DIDN'T reduce Fv DNA (P = 0.1846)
SDS.qPCR.t2 #For exp2, fluopyram reduced Fv DNA (P = 1.405e-05)


#Repeat analyses within variety within rep
exp1.SCN.qpcr.df.A <- exp1.SCN.qpcr.df[exp1.SCN.qpcr.df$Var=="A",]
exp1.SCN.qpcr.df.B <- exp1.SCN.qpcr.df[exp1.SCN.qpcr.df$Var=="B",]
exp2.SCN.qpcr.df.A <- exp2.SCN.qpcr.df[exp2.SCN.qpcr.df$Var=="A",]
exp2.SCN.qpcr.df.B <- exp2.SCN.qpcr.df[exp2.SCN.qpcr.df$Var=="B",]
exp1.SDS.qpcr.df.A <- exp1.SDS.qpcr.df[exp1.SDS.qpcr.df$Var=="A",]
exp1.SDS.qpcr.df.B <- exp1.SDS.qpcr.df[exp1.SDS.qpcr.df$Var=="B",]
exp2.SDS.qpcr.df.A <- exp2.SDS.qpcr.df[exp2.SDS.qpcr.df$Var=="A",]
exp2.SDS.qpcr.df.B <- exp2.SDS.qpcr.df[exp2.SDS.qpcr.df$Var=="B",]

#SCN qpcr data for variety A
SCN.qPCR.A1 <- t.test(Quantity.Mean ~ Trt, data = exp1.SCN.qpcr.df.A)
SCN.qPCR.A2 <- t.test(Quantity.Mean ~ Trt, data = exp2.SCN.qpcr.df.A)
SCN.qPCR.A1 #For exp1, fluopyram had no effect on SCN DNA in Variety A
SCN.qPCR.A2 #For exp2, fluopyram had no effect on SCN DNA in Variety A
#SCN qpcr data for variety B
SCN.qPCR.B1 <- t.test(Quantity.Mean ~ Trt, data = exp1.SCN.qpcr.df.B)
SCN.qPCR.B2 <- t.test(Quantity.Mean ~ Trt, data = exp2.SCN.qpcr.df.B)
SCN.qPCR.B1 #For exp1, fluopyram REDUCED SCN DNA in Variety B (P = 0.0001)
SCN.qPCR.B2 #For exp2, fluopyram had no effect on SCN DNA in Variety B (P = 0.09)

#SDS qpcr data for variety A
#Looks like Base + fluopyram biological rep 3 in variety A is a major outlier
# A3                            = 395663.3282
# Next highest in same category =  15263.0312
# Removing outlier does not change outcome
# exp1.SDS.qpcr.df.A <- exp1.SDS.qpcr.df.A[-c(17:18),]
SDS.qPCR.A1 <- t.test(Quantity.Mean ~ Trt, data = exp1.SDS.qpcr.df.A)
SDS.qPCR.A2 <- t.test(Quantity.Mean ~ Trt, data = exp2.SDS.qpcr.df.A)
SDS.qPCR.A1 #For exp1, fluopyram had no effect on Fv DNA in Variety A
SDS.qPCR.A2 #For exp2, fluopyram REDUCED Fv DNA in Variety A (P = 0.00018)
#SDS qpcr data for variety B
SDS.qPCR.B1 <- t.test(Quantity.Mean ~ Trt, data = exp1.SDS.qpcr.df.B)
SDS.qPCR.B2 <- t.test(Quantity.Mean ~ Trt, data = exp2.SDS.qpcr.df.B)
SDS.qPCR.B1 #For exp1, fluopyram REDUCED Fv DNA in Variety B (P = 0.0004377)
SDS.qPCR.B2 #For exp2, fluopyram REDUCED Fv DNA in Variety B (P = 0.006573)

```

```{r plots}
library(plyr)
library(ggplot2)
library(ggpubr)
#Experiment 1 plots
colnames(exp1.df)
p1 <- ggplot(data = exp1.df, aes(x = Entry.Treatment,
                                y = SCN.F.Cyst, 
                                fill = Entry.Treatment)) +
    stat_summary(fun.y = mean, position="identity", geom = "bar") +
    stat_summary(fun.data = mean_se, 
                 position = "identity", 
                 geom = "errorbar",
                 width = 0.5) +
    stat_compare_means(size = 5, 
                       label = "p.signif", 
                       method = "t.test",
                       label.y.npc = 0.85) +
    facet_grid(~Soybean.Variety, switch="x") +
    xlab("Cultivar") + ylab("SCN Females + Cysts") +
    ggtitle("Response to fluopyram in Greenhouse") +
    theme_bw() +
    theme(legend.title=element_text(size=12), legend.text=element_text(size=20),
          legend.position="bottom", strip.text.x = element_text(size=18),
          axis.text.x=element_blank(), axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=28, face="bold"), 
          axis.title.y=element_text(size=28, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank(), panel.grid.minor=element_blank(),
          panel.grid.major=element_blank()) +
  scale_fill_grey()
p1

colnames(exp1.SCN.qpcr.df)
p1.2 <- ggplot(data = exp1.SCN.qpcr.df, aes(x = Trt, 
                                       y = Quantity.Mean, 
                                       fill = Trt)) +
    stat_summary(fun.y = mean, position="identity", geom = "bar") +
    stat_summary(fun.data = mean_se, position = "identity", geom = "errorbar",
               width = 0.5) +
    stat_compare_means(size = 5, label = "p.signif", method = "t.test",
                       label.y.npc = 0.75) +
    facet_grid(~Var, switch="x") +
    xlab("Cultivar") + ylab("SCN DNA Quantity (pg)") +
    ggtitle("Response to fluopyram in Greenhouse") +
    theme_bw() +
    theme(legend.title=element_text(size=12), legend.text=element_text(size=20),
          legend.position="bottom", strip.text.x = element_text(size=18),
          axis.text.x=element_blank(), axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=28, face="bold"), 
          axis.title.y=element_text(size=28, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank(), panel.grid.minor=element_blank(),
          panel.grid.major=element_blank()) +
  scale_fill_grey()
p1.2

colnames(exp1.SDS.qpcr.df)
#Need to remove outlier in Var A experiment 1
order(exp1.SDS.qpcr.df$Quantity.Mean)
exp1.SDS.qpcr.df <- exp1.SDS.qpcr.df[-c(17:18),]
#Also, convert pg to ng by / 1000
exp1.SDS.qpcr.df$Quantity.Mean <- (exp1.SDS.qpcr.df$Quantity.Mean / 1000)
p1.3 <- ggplot(data = exp1.SDS.qpcr.df, aes(x = Trt, 
                                       y = Quantity.Mean, 
                                       fill = Trt)) +
    stat_summary(fun.y = mean, position="identity", geom = "bar") +
    stat_summary(fun.data = mean_se, position = "identity", geom = "errorbar",
               width = 0.5) +
    stat_compare_means(size = 5, label = "p.signif", method = "t.test",
                       label.y.npc = 0.65) +
    facet_grid(~Var, switch="x") +
    xlab("Cultivar") + ylab("F. virguliforme quantity (ng)") +
    ggtitle("Response to ILeVO in Greenhouse") +
    theme_bw() +
    theme(legend.title=element_text(size=12), legend.text=element_text(size=20),
          legend.position="bottom", strip.text.x = element_text(size=18),
          axis.text.x=element_blank(), axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=28, face="bold"), 
          axis.title.y=element_text(size=28, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank(), panel.grid.minor=element_blank(),
          panel.grid.major=element_blank()) +
  scale_fill_grey()

p1.3

library(gridExtra)
grid.arrange(p1,p1.2,p1.3,ncol=3)




#Experiment 2 plots
colnames(exp2.df)
p2 <- ggplot(data = exp2.df, aes(x = Entry.Treatment,
                                y = SCN.F.Cyst, 
                                fill = Entry.Treatment)) +
    stat_summary(fun.y = mean, position="identity", geom = "bar") +
    stat_summary(fun.data = mean_se, 
                 position = "identity", 
                 geom = "errorbar",
                 width = 0.5) +
    stat_compare_means(size = 5, 
                       label = "p.signif", 
                       method = "t.test",
                       label.y.npc = 0.85) +
    facet_grid(~Soybean.Variety, switch="x") +
    xlab("Cultivar") + ylab("SCN Females + Cysts") +
    ggtitle("Response to fluopyram in Greenhouse") +
    theme_bw() +
    theme(legend.title=element_text(size=12), legend.text=element_text(size=20),
          legend.position="bottom", strip.text.x = element_text(size=18),
          axis.text.x=element_blank(), axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=28, face="bold"), 
          axis.title.y=element_text(size=28, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank(), panel.grid.minor=element_blank(),
          panel.grid.major=element_blank()) +
  scale_fill_grey()
p2

colnames(exp2.SCN.qpcr.df)
p2.2 <- ggplot(data = exp2.SCN.qpcr.df, aes(x = Trt, 
                                       y = Quantity.Mean, 
                                       fill = Trt)) +
    stat_summary(fun.y = mean, position="identity", geom = "bar") +
    stat_summary(fun.data = mean_se, position = "identity", geom = "errorbar",
               width = 0.5) +
    stat_compare_means(size = 5, label = "p.signif", method = "t.test",
                       label.y.npc = 0.75) +
    facet_grid(~Var, switch="x") +
    xlab("Cultivar") + ylab("SCN DNA Quantity (pg)") +
    ggtitle("Response to fluopyram in Greenhouse") +
    theme_bw() +
    theme(legend.title=element_text(size=12), legend.text=element_text(size=20),
          legend.position="bottom", strip.text.x = element_text(size=18),
          axis.text.x=element_blank(), axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=28, face="bold"), 
          axis.title.y=element_text(size=28, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank(), panel.grid.minor=element_blank(),
          panel.grid.major=element_blank()) +
  scale_fill_grey()
p2.2

colnames(exp1.SDS.qpcr.df)
#Convert pg to ng by / 1000
exp2.SDS.qpcr.df$Quantity.Mean <- (exp2.SDS.qpcr.df$Quantity.Mean / 1000)
p2.3 <- ggplot(data = exp2.SDS.qpcr.df, aes(x = Trt, 
                                       y = Quantity.Mean, 
                                       fill = Trt)) +
    stat_summary(fun.y = mean, position="identity", geom = "bar") +
    stat_summary(fun.data = mean_se, position = "identity", geom = "errorbar",
               width = 0.5) +
    stat_compare_means(size = 5, label = "p.signif", method = "t.test",
                       label.y.npc = 0.65) +
    facet_grid(~Var, switch="x") +
    xlab("Cultivar") + ylab("F. virguliforme quantity (ng)") +
    ggtitle("Response to ILeVO in Greenhouse") +
    theme_bw() +
    theme(legend.title=element_text(size=12), legend.text=element_text(size=20),
          legend.position="bottom", strip.text.x = element_text(size=18),
          axis.text.x=element_blank(), axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=28, face="bold"), 
          axis.title.y=element_text(size=28, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank(), panel.grid.minor=element_blank(),
          panel.grid.major=element_blank()) +
  scale_fill_grey()

p2.3

library(gridExtra)
grid.arrange(p2,p2.2,p2.3,ncol=3)
```

```{r}
syn.master <- read.csv2("SDS_and_SCN_qPCR.csv", header = TRUE, sep = ",")
colnames(syn.master)
#Note, SCN_quant is already in pg, so ignore SCN_quant2
syn.df <- syn.master
#convert quantities from factor to numeric, change Fv to picograms (fg / 1000)
syn.df$Fv_quant <- as.numeric(as.character(syn.df$Fv_quant))/1000
syn.df$SCN_quant <- as.numeric(as.character(syn.df$SCN_quant))

syn.df1 <- syn.df[syn.df$Experiment=="1",]
syn.df2 <- syn.df[syn.df$Experiment=="2",]

library(ggplot2)
library(ggpubr)
colnames(syn.df1)
# Remove outliers
order(syn.df1$Fv_quant)
syn.df1 <- syn.df1[-c(17:18),]
p1s <- ggplot(data = syn.df1, aes(x = Fv_quant, y = SCN_quant,
                                shape = Trt),
             colour = Variety) +
  geom_point(shape = c(24, 21)[as.factor(syn.df1$Variety)],
             colour = "black",
             aes(fill = syn.df1$Trt),
             size = 10) +  
  stat_ellipse(level = 0.95, aes(linetype = as.factor(syn.df1$Trt))) +
  #geom_text(label=syn.df$Variety,
  #          size = 5,
  #          colour = "white",
  #          fontface="bold") +
      ylab("SCN DNA Quantity (pg)") + xlab("Fv DNA Quantity (pg)") +
  xlim(-1.2,10) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.text=element_text(size=28), legend.position="",
        axis.text.x=element_text(size=28), strip.text.x = element_text(size=18),
        axis.title.x=element_text(size=28, face="bold"),
        axis.title.y=element_text(size=28, face="bold"),
        axis.text.y=element_text(size=28)) +
  scale_fill_grey() 
p1s

colnames(syn.df2)
p2s <- ggplot(data = syn.df2, aes(x = Fv_quant, y = SCN_quant,
                                shape = Trt),
             colour = Variety) +
  geom_point(shape = c(24, 21)[as.factor(syn.df2$Variety)],
             colour = "black",
             aes(fill = syn.df2$Trt),
             size = 10) +  
  stat_ellipse(level = 0.95, aes(linetype = as.factor(syn.df2$Trt))) +
  #geom_text(label=syn.df$Variety,
  #          size = 5,
  #          colour = "white",
  #          fontface="bold") +
      ylab("SCN DNA Quantity (pg)") + xlab("Fv DNA Quantity (pg)") +
  #xlim(-1.2,10) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.text=element_text(size=28), legend.position="",
        axis.text.x=element_text(size=28), strip.text.x = element_text(size=18),
        axis.title.x=element_text(size=28, face="bold"),
        axis.title.y=element_text(size=28, face="bold"),
        axis.text.y=element_text(size=28)) +
  scale_fill_grey() 
p2s

grid.arrange(p1s, p2s, ncol=2)
```

